server {
    listen 80;
    server_name office.sousaediasadvogados.pt;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name office.sousaediasadvogados.pt;

    # SSL preenchido pelo certbot automaticamente

    location / {
        proxy_pass http://localhost:3200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection '';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    location /events {
        proxy_pass http://localhost:3200/events;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
        chunked_transfer_encoding on;
        add_header Cache-Control no-cache;
        add_header X-Accel-Buffering no;
    }
}
